Repository hyunbin-and-ddakkarri/food-finder, pull requests merged in 2023-05, with the labels that each got.

#16 Add dockerfiles for admin & public
  .github/workflows/docker.yaml
  admin.Dockerfile
  admin/next.config.js
  admin/nginx.conf
  public.Dockerfile
  public/next.config.js
  public/nginx.conf
  public/tsconfig.json
Labels: Setup

#22 GraphQL setup complete
  server/schema.py
Labels: server

#23 README
  server/README.md
Labels: documentation
