Repository hyunbin-and-ddakkarri/food-finder, pull requests merged in 2023-06, with the labels that each got.

#33 Add pytest for github action
  .github/workflows/data.yaml
  .github/workflows/server.yaml
  data/data/map/naver.py
  data/poetry.lock
  data/pyproject.toml
  server/poetry.lock
  server/pyproject.toml
  server/server/schema.py
  server/tests/test_simple.py
Labels: Setup

#34 Add badges and introduction to README.md
  README.md
  docs/food-finder-sdd-team2.pdf
  docs/food-finder-srs-team13.pdf
Labels: documentation

#35 add test & coverage for nextjs
  .github/workflows/admin.yaml
  .github/workflows/public.yaml
  admin/__test__/page.test.tsx
  admin/jest.config.mjs
  admin/package-lock.json
  admin/package.json
  public/__test__/page.test.tsx
  public/jest.config.mjs
  public/package-lock.json
  public/package.json
Labels: Setup

#49 Fix test to success when 429 error
  data/data/map/naver.py
Labels: data-scrapping

#57 Update dependabot-automerge.yaml
  .github/workflows/dependabot-automerge.yaml
Labels: Setup

#62 Add docker compose
  .env.sample
  .gitignore
  README.md
  admin.Dockerfile
  data/data/map/naver.py
  data/poetry.lock
  docker-compose.yaml
  nginx.conf
  public.Dockerfile
  server/poetry.lock
Labels: Setup

#85 Frontend development
  .gitignore
  admin/src/app/category/catcell.tsx
  admin/src/app/category/page.tsx
  admin/src/app/globals.css
  admin/src/app/layout.tsx
  admin/src/app/restaurant/page.tsx
  data/poetry.lock
  package.json
  public/.gitignore
  public/__test__/page.test.tsx
  public/_document.js
  public/manifest.json
  public/next.config.js
  public/package-lock.json
  public/package.json
  public/public/img/Chinese.jpg
  public/public/img/Chinese/Malatang.jpg
  public/public/img/Italian.jpg
  public/public/img/Italian/Pizza.jpg
  public/public/img/Italian/Spaghetti.jpg
  public/public/img/Japanese.jpg
  public/public/img/Japanese/Donburi.jpeg
  public/public/img/Japanese/Donburi.jpg
  public/public/img/Japanese/Ramen.jpeg
  public/public/img/Japanese/Ramen.jpg
  public/public/img/Japanese/Sushi.jpeg
  public/public/img/Japanese/Sushi.jpg
  public/public/img/Korean.jpg
  public/public/img/Korean/Bibimbap.jpg
  public/public/img/Korean/Bulgogi.jpg
  public/public/img/Korean/Ddeokbokki.jpg
  public/public/img/Korean/Jokbal.jpg
  public/public/img/icons/icon-192x192.png
  public/public/img/icons/icon-256x256.png
  public/public/img/icons/icon-384x384.png
  public/public/img/icons/icon-512x512.png
  public/public/img/logo.png
  public/src/app/datamap/[...region]/page.tsx
  public/src/app/filters.tsx
  public/src/app/globals.css
  public/src/app/layout.tsx
  public/src/app/listview/[...region]/detail.tsx
  public/src/app/listview/[...region]/page.tsx
  public/src/app/loading.tsx
  public/src/app/map/[...region]/page.tsx
  public/src/app/page.tsx
  public/src/app/region.tsx
  public/src/app/restaurant.tsx
  public/src/app/searchbar.tsx
  public/tailwind.config.js
  public/tsconfig.json
  public/yarn.lock
  server/.gitignore
  server/poetry.lock
Labels: public
